# Generated by Django 3.1 on 2021-01-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='engine',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='image_1',
            field=models.ImageField(default='', upload_to='myapp/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_10',
            field=models.ImageField(default='', upload_to='myapp/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(default='', upload_to='myapp/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(default='', upload_to='myapp/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(default='', upload_to='myapp/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_5',
            field=models.ImageField(default='', upload_to='myapp/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_6',
            field=models.ImageField(default='', upload_to='myapp/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_7',
            field=models.ImageField(default='', upload_to='myapp/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_8',
            field=models.ImageField(default='', upload_to='myapp/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_9',
            field=models.ImageField(default='', upload_to='myapp/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='kilometers_driven',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='transmission',
            field=models.CharField(default='', max_length=20),
        ),
    ]
