# Generated by Django 3.1 on 2021-01-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210126_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='myapp/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_10',
            field=models.ImageField(blank=True, upload_to='myapp/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='myapp/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='myapp/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='myapp/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_5',
            field=models.ImageField(blank=True, upload_to='myapp/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_6',
            field=models.ImageField(blank=True, upload_to='myapp/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_7',
            field=models.ImageField(blank=True, upload_to='myapp/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_8',
            field=models.ImageField(blank=True, upload_to='myapp/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_9',
            field=models.ImageField(blank=True, upload_to='myapp/images/'),
        ),
    ]
