# Generated by Django 3.1 on 2021-01-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210126_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='transmission',
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.CharField(default='', max_length=20),
        ),
    ]
