# Generated by Django 3.1 on 2021-01-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210126_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='myapp/images/{{product.product_name}}'),
        ),
    ]
